server {
    listen 80;
    server_name _;
    absolute_redirect off;
    root /usr/share/nginx/html;

    location ~ ^/home(?:|/index|/search|/about|/about/submissions|/about/privacy|/announcement/view/12)$ {
        try_files /mirror$uri.html @app;
    }

    location = / {
        return 302 /home;
    }

    location @app {
        proxy_pass http://app:80;
        proxy_set_header Host $http_host;
        proxy_set_header X-Forwarded-Host $http_host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_redirect off;
    }

    location / {
        try_files $uri @app;
    }
}
